[theme]
base = "light"

primaryColor = "#140a9a"  # BHP orange
backgroundColor = "#FFFFFF"  # White
secondaryBackgroundColor = "#f0f1f5"  # Light gray for contrast
textColor = "#000000"  # Black for text


#primaryColor = "#140a9a"

#[server]
#fileWatcherType = "poll"
#password = "derek"
#backgroundColor = "#F0FF33"
#secondaryBackgroundColor = "#3183D1"
#textColor = "#03080C"
#font = "sans-serif"